### ISSUE TITLE
Center aligned description should be removed 

### ISSUE THREAD

**Issue by radzhiv25** [ayushsoni1010/portfolio#8]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/84130482/198955192-13d510be-cfce-4b6e-9658-7877aaa21c88.png">
As it would be more appealing without it 
(Hello, I'm a full stack developer based in India)

**Comment by ayushsoni1010** [comment]
Hey @radzhiv25 👋
I have taken the UI inspiration from this website [SaaS UI](https://saas-ui.dev/), `Hello, I'm a Full Stack Developer based in India` button is used for the external link and one more purpose to use is to show a headline like a developer from India :)

I would love to know more feedback
Thanks for showing man!
